#pragma once

using namespace ATL;

template <class T>
class CProxy_IUCRC32Events : public IConnectionPointImpl<T, &__uuidof( _IUCRC32Events ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
